#page title -- bundle exec jekyll serve
page_title                                : Katzenjammer                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : #1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : mailto:hello@katzenjammer-games.ca       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Katzenjammer                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : An AR Party Game. Your Friends. Your Rules. Your Game.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Katzenjammer Games Ltd.                                
your_link                                 : https://katzenjammer-games.ca                     
your_city                                 : Canada                                
email_address                             : hello@katzenjammer-games.ca
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : katzenjammerG
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Card Game + Tech Magic
    description                           : Katzenjammer is a card game that can only be described as a cosmic gumbo of Uno, Truth or dare, and a misinterpretation of how Yu-Gi-Oh works. Oh, and it also uses Augmented Reality for some reason.
    fontawesome_icon_name                 : magic
    
  - title                                 : A Brand New Party Game Experience
    description                           : Unlike similar party games, where the dares on the cards are soft to avoid liability, we put the responsibility on our players to not kill themselves. You create you own dares right in the app. No external servers needed. 
    fontawesome_icon_name                 : mobile

  - title                                 : Augmented Reality
    description                           : Use the power of Augmented Reality to play your game. Create new decks so your game never gets stale. With AR no one knows what dares are on each card until viewed throught the app.
    fontawesome_icon_name                 : play-circle

  - title                                 : Capture your Memories
    description                           : Record your games with ease. Capture the craziest moments from your game and share them with the friend who bailed.
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Create new dares with ease. Depending on whos playing, you can select the type of memories you want to make. With private inputs no one knows what dares everyone else wrote until you scan the cards using AR.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : We are consistently improving gameplay an app functionality. New AR gimmicks always being added. No need to buy a new deck with every update.
    fontawesome_icon_name                 : star

  - title                                 : #Smart App Banner
    description                           : #Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : #arrow-alt-circle-down

  - title                                 : #Social Links
    description                           : #Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #link

  - title                                 : #FontAwesome Support
    description                           : #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#3689C6"

link_color                                : "#FFF1F2"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#3689C6"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#3689C6"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#FFF1F2"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown